# Generated by Django 5.2.9 on 2026-03-09 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], verbose_name='Day of Week')),
                ('start_time', models.TimeField(default='09:00:00', verbose_name='Start Time')),
                ('end_time', models.TimeField(default='18:00:00', verbose_name='End Time')),
                ('is_day_off', models.BooleanField(default=False, verbose_name='Day Off')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='booking_app.provider', verbose_name='Provider')),
            ],
            options={
                'ordering': ['day_of_week'],
                'unique_together': {('owner', 'provider', 'day_of_week')},
            },
        ),
    ]
