# Generated by Django 5.2.9 on 2026-03-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0002_workinghours'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingservice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='booking_services/', verbose_name='Service Image'),
        ),
        migrations.AddField(
            model_name='provider',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='providers/', verbose_name='Provider Avatar'),
        ),
    ]
