# Generated by Django 5.2.9 on 2026-03-11 10:52

import core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0003_bookingservice_image_provider_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservation_number',
            field=models.CharField(editable=False, max_length=14, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='bookingservice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='booking_services/', validators=[core.validators.validate_is_image], verbose_name='Service Image'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('active', 'New'), ('completed', 'Completed'), ('cancelled_by_customer', 'Cancelled by Customer'), ('cancelled_by_seller', 'Cancelled by Seller')], default='active', max_length=30, verbose_name='Status'),
        ),
    ]
