# Generated by Django 5.2.9 on 2026-03-11 11:45

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0005_alter_reservation_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='providers/', validators=[core.validators.validate_is_image], verbose_name='Provider Avatar'),
        ),
    ]
