# Generated by Django 5.2.9 on 2026-03-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0006_alter_provider_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingservice',
            name='booking_type',
            field=models.CharField(choices=[('slots', '15-minute Slots'), ('exact_time', 'Exact Time (Start only)')], default='slots', max_length=20, verbose_name='Booking Type'),
        ),
        migrations.AlterField(
            model_name='bookingservice',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End Time'),
        ),
    ]
