# Generated by Django 5.2.9 on 2026-03-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0007_bookingservice_booking_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingservice',
            name='providers',
            field=models.ManyToManyField(blank=True, related_name='services', to='booking_app.provider', verbose_name='Providers'),
        ),
        migrations.AlterField(
            model_name='bookingservice',
            name='booking_type',
            field=models.CharField(choices=[('slots', '15-minute Slots'), ('exact_time', 'Exact Time (Start and End)')], default='slots', max_length=20, verbose_name='Booking Type'),
        ),
    ]
