# Generated by Django 5.2.9 on 2025-12-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_en', models.TextField(verbose_name='Footer Text (EN)')),
                ('text_es', models.TextField(verbose_name='Footer Text (ES)')),
            ],
            options={
                'verbose_name': 'Footer',
                'verbose_name_plural': 'Footer',
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Maintenance Active?')),
                ('message_en', models.TextField(verbose_name='Message (EN)')),
                ('message_es', models.TextField(verbose_name='Message (ES)')),
            ],
            options={
                'verbose_name': 'Maintenance Mode',
                'verbose_name_plural': 'Maintenance Mode',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=100, verbose_name='Title (EN)')),
                ('title_es', models.CharField(max_length=100, verbose_name='Title (ES)')),
                ('url', models.CharField(max_length=200, verbose_name='External URL / Relative path')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=200, verbose_name='Title (EN)')),
                ('content_en', models.TextField(verbose_name='Content (EN)')),
                ('slug_en', models.SlugField(max_length=200, unique=True, verbose_name='URL Slug (EN)')),
                ('title_es', models.CharField(max_length=200, verbose_name='Title (ES)')),
                ('content_es', models.TextField(verbose_name='Content (ES)')),
                ('slug_es', models.SlugField(max_length=200, unique=True, verbose_name='URL Slug (ES)')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
            },
        ),
    ]
