# Generated by Django 5.2.9 on 2025-12-18 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_menuitem_linked_page_alter_menuitem_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.menuitem', verbose_name='Parent Item'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='linked_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.page', verbose_name='Linked Page'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='External URL'),
        ),
    ]
