# Generated by Django 5.2.9 on 2025-12-19 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_menuitem_parent_alter_menuitem_linked_page_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='linked_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_items', to='core.page', verbose_name='Linked Page'),
        ),
    ]
