# Generated by Django 5.2.9 on 2026-03-04 16:05

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_menuitem_linked_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content_en',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content (EN)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content_es',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content (ES)'),
        ),
    ]
