# Generated by Django 5.2.9 on 2026-03-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0005_customuser_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sku_limit',
            field=models.PositiveIntegerField(default=10, verbose_name='SKU Limit'),
        ),
    ]
