# Generated by Django 5.2.9 on 2026-03-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0006_customuser_sku_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='show_in_catalog',
            field=models.BooleanField(default=False, verbose_name='Show in Catalog'),
        ),
    ]
