# Generated by Django 5.2.9 on 2026-03-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0009_alter_customuser_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
