# Generated by Django 5.2.9 on 2026-03-11 11:37

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0011_alter_customuser_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[core.validators.validate_is_image], verbose_name='Avatar'),
        ),
    ]
