# Generated by Django 5.2.9 on 2026-03-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0012_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro (€)'), ('USD', 'US Dollar ($)'), ('ARS', 'Argentine Peso (ARS$)')], default='EUR', max_length=3, verbose_name='Currency'),
        ),
    ]
