# Generated by Django 5.2.9 on 2026-03-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0013_customuser_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='max_providers',
            field=models.IntegerField(default=3, help_text='Maximum number of providers this user can create.', verbose_name='Maximum Providers'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='max_services',
            field=models.IntegerField(default=3, help_text='Maximum number of services this user can create.', verbose_name='Maximum Services'),
        ),
    ]
