# Generated by Django 5.2.9 on 2026-03-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0004_order_status_ordercomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('active', 'New'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled_by_buyer', 'Cancelled by Buyer'), ('cancelled_by_seller', 'Cancelled by Seller')], default='active', max_length=30, verbose_name='Status'),
        ),
    ]
