# Generated by Django 5.2.9 on 2026-03-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0007_alter_order_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(editable=False, max_length=12, null=True, unique=True),
        ),
    ]
